# 手动编译Tvbox，内置了2个。
# 2023年2月1日16:38:25
name: 手动编译Tvbox，并上传至Releases。

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: '选择编译来源'
        options:
        - https://github.com/q215613905/TVBoxOS
        - https://github.com/takagen99/Box
        default: 'https://github.com/takagen99/Box'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get-project
        name: Time
        run: |
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "NAME=$(echo ${{ github.event.inputs.target }} | cut -d '/' -f 4- | cut -d '/' -f 1)" >> $GITHUB_ENV
      - name: Clone project
        run: git clone --depth=1 ${{ github.event.inputs.target }} project
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Test Rename
        working-directory: ./project
        run: |
          mv ./app/build/outputs/apk/debug/app-debug.apk ./app/build/outputs/apk/debug/Tvbox-${{ env.NAME }}-${{ env.FILE_DATE }}.apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Tvbox-${{ env.NAME }}-${{ env.FILE_DATE }}
          path: ./**/*.apk
      - name: 发布到Release
        uses: softprops/action-gh-release@v1
        with:
          name: Tvbox-${{ env.NAME }}-${{ env.FILE_DATE }}
          tag_name: Tvbox-${{ env.NAME }}-${{ env.FILE_DATE }}
#          body_path: /project/README.md
          draft: false
          prerelease: false
          files: ./**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}