name: 手动选择编译安卓APK

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: '选择编译来源'
        options:
        - https://github.com/q215613905/TVBoxOS
        - https://github.com/takagen99/Box
        default: 'https://github.com/takagen99/Box'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Time
        run: |
          sudo apt-get update
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo ${{ github.event.inputs.target }} | cut -d '/' -f 4- | cut -d '/' -f 1
      - name: Clone project
        run: git clone --depth=1 ${{ github.event.inputs.target }} project
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk-${{ env.FILE_DATE }}
          path: ./**/*.apk